### ISSUE TITLE
Segmentation fault in run_assistant_file.

### ISSUE THREAD

**Issue by mohit-thakur-721** [googlesamples/assistant-sdk-cpp#63] opened 2019-07-06 09:04 UTC
The sample command failed.
./run_assistant_file --input ./resources/weather_in_mountain_view.raw --output ./response.wav --credentials ./credentials.json

terminate called without an active exception
Aborted (core dumped)

 i found that the chunk variable in AudioInputFile::GetBackgroundThread() is not able to alloacte the memory.

**Comment by Fleker** [comment] 2019-07-08 17:07
Duplicate of #62

**Closed as completed by Fleker** 2019-07-08 17:07 UTC
